== 比赛体系
=== 公正的角色
要在小型组中进行正式比赛，必须满足四个公正的角色：

* <<_裁判, 裁判>>
* <<_助理裁判, 助理裁判>>
* <<_指令软件操作员, 指令软件操作员>>
* <<_图像专家, 图像专家>>

通常，这些角色由两个非参赛队伍担任，其中一个队伍提供<<_裁判, 裁判>>和<<_指令软件操作员, 指令软件操作员>>，另一个队伍提供<<_助理裁判, 助理裁判>>和<<_图像专家, 图像专家>>。 角色的分配由<<_组织委员会, 委员会>>决定。每个参赛团队的成员都必须熟悉这些人员。

==== 裁判
每场比赛由裁判控制。他完全有权执行小型组比赛相关的规则。建议裁判使用场地旁边的指定步行区域（参见<<_场地设置, 场地设置>>）。

裁判由<<_自动裁判软件, 自动裁判软件>>协助。允许裁判覆盖裁判软件做出的任何决定。

裁判关于与比赛有关的裁决是最终的。裁判只能改变自己认为不正确的决定，或者由他自行决定更改助理裁判的建议，但他不能重新开始比赛。

裁判员不对任何官员或旁观者遭受的任何伤害，任何形式的财产损失或个人，俱乐部，公司，协会或其他机构遭受的任何其他损失承担责任。

<<_团队负责人, 团队负责人>>是唯一的可以与裁判交谈的团队成员。

.任务

* 裁判为所有的人和机器人确保了一个安全的比赛
* 裁判根据小型组的规则确保了一个相对公平的比赛
* 裁判确保未经授权的人员或团队成员不会干涉比赛
* 裁判或助理裁判将球放置于<<_开球, 开球>>，<<_点球, 点球>>或每次<<_停止比赛, 停止比赛>>位置之后，裁判恢复比赛
* 裁判确保比赛开始并及时恢复

==== 助理裁判
助理裁判(Assistant Referee)在任何可能的地方支持裁判。并且被鼓励存在于裁判员对面的<<_场地设置, 场地>>旁边的指定步行区。

参赛队伍的成员不被允许与助理裁判交谈

.任务

* 当发生的一些不当行为或任何其他事件在裁判视野之外时,助理裁判应当指出
* 助理裁判与裁判讨论不能清楚裁决的情况
* 裁判或助理裁判将球放置于<<_开球, 开球>>，<<_点球, 点球>>或每次<<_停止比赛, 停止比赛>>位置之后，裁判恢复比赛


==== 指令软件操作员
在比赛期间，指令软件操作员(Game Controller Operator)使用<<_比赛指令软件, 比赛指令软件>>作为<<_裁判, 裁判>>,<<_自动裁判软件, 自动裁判软件>>和团队软件之间的接口。

参赛队伍的成员不允许与指令软件操作员交谈,除非<<_团队负责人, 团队负责人>>要求<<_机器人更换, 更换机器人>>的情况。

.任务
* 指令软件操作员在比赛开始之前配置<<_比赛指令软件, 比赛指令软件>>
* 指令软件操作员将<<_裁判, 裁判>>的信号输入到<<_比赛指令软件, 比赛指令软件>>中
* 指令软件操作员在比赛事件日志中查看需要注意的事件，例如<<_自动裁判软件, 自动裁判软件>>或经过的计时器的检测，并通知<<_裁判, 裁判>>

==== 视觉专家
在比赛期间，视觉专家(Vision Expert)负责该场地的<<_共享视觉系统, 共享视觉系统>>。

通常建议团队成员不要与视觉专家交谈，除非他们遇到重大视觉方面的问题。

.任务
* 视觉专家检查视觉硬件并向<<_技术委员会, 技术委员会>>报告任何类型的硬件问题
* 视觉专家在比赛期间监控共享视觉系统，并立即向裁判报告任何类型的问题
* 如果裁判认为有必要，视觉专家会重新校准视觉系统

=== 团队特定角色

==== 团队负责人
在比赛开始之前，每个团队都必须指定一个团队负责人(Robot Handler)。团队负责人在比赛期间代表该团队比赛。

.任务
* 团队负责人有义务协助<<_比赛准备, 准备比赛>>。
* 如有必要，团队负责人可以向裁判申请<<_暂停, 暂停>>。
* 团队负责人要求裁判在下一次停止时更换机器人，如果裁判同意，则<<_机器人更换, 更换机器人>>。
* 团队负责人反映团队比较关心的问题（例如网络问题或视觉问题）。

=== 比赛准备
所有在比赛中发挥作用的人（<<_公正的角色, 裁判方>>或者<<_团队特定角色, 队伍方>>）必须在比赛开始前至少10分钟做好以下准备：

==== 比赛结果表
<<_裁判, 裁判>>从<<_组织委员会, 委员会>>获得比赛结果表格。 比赛结束后，裁判填写最终比分，收集所需签名，并将表格提交给<<_组织委员会, 委员会>>。

NOTE: 在获得比赛结果表时，裁判还可以使用官方的<<_比赛用球, 比赛用球>>和裁判设备，如哨子或红牌和黄牌（如果提供的话）。

==== 测试网络
<<_裁判, 裁判>>确保两支球队都能获得视觉数据和裁判命令。

==== 选择团队颜色
<<_裁判, 裁判>>询问球队的<<_团队负责人, 团队负责人>>，选择他们更倾向的球队颜色（蓝色或黄色）。 如果团队同意颜色分配，颜色将用于整个比赛。

但是，如果两队都倾向于一个相同的颜色，裁判会随机分配颜色。 在这种情况下，球队在比赛的前半段之后以及加时赛的前半段之后切换颜色（如果适用）。

==== 选择半场和开球
<<_裁判, 裁判>>向<<_团队负责人, 团队负责人>>投掷硬币。 获胜队将在比赛的前半段选择进攻的目标。 另一支球队以<<_开球, 开球>>开始比赛。

==== 选择守门员ID
<<_裁判, 裁判>>询问<<_团队负责人, 团队负责人>>他们将使用哪个机器人作为守门员，并将此信息告诉给<<_指令软件操作员, 指令软件操作员>>。

NOTE: 如果团队不想使用守门员，则可以选择不在场上的机器人的ID。

=== 比赛阶段
==== 概述
小型组的官方比赛包括以下几个阶段：

|===
| 比赛阶段 | 时长

| 上半场 | 比赛时间 300 秒
| 中场休息 | 暂停 300 秒
| 下半场 | 比赛时间 300 秒
|===

如果比赛是淘汰赛（比赛结果不可以是平局），并且在正常比赛时间之后比分相同，比赛将进入加时赛，并添加以下比赛阶段：

|===
| 比赛阶段 | 时长

| 加时赛前休息 | 暂停 300 秒
| 加时赛上半场 | 比赛时间 150 秒
| 加时赛中场休息 | 暂停 120 秒
| 加时赛下半场 | 比赛时间 150 秒
|===

如果加时赛后双方比分仍相等, 则添加以下比赛阶段:

|===
| 比赛阶段 | 时长

| 点球大战前休息 | 暂停 120 秒
| <<_点球大战, 点球大战>> | 无限制时长
|===

只要没有球队被允许进行<<_碰球操作, 碰球操作>>，比赛计时器就会暂停。 这包括<<_停止, 停止>>，<<_终止, 终止>>以及<<_开球, 开球>>和<<_点球, 点球>>的准备状态。 此外，计时器在<<_放球, 放球>>期间也会暂停。

NOTE: 因此，比赛所需的时间远远大于比赛时间。

==== 暂停
<<_团队负责人, 团队负责人>>必须向裁判请求暂停。 暂停的处理方式类似于<<_概述, 间隔休息>>，这意味着允许两个团队对其软件和硬件进行修改（参见<<_自主运行,自主运行>>）。

每支球队在比赛开始时分配4次暂停。 所有暂停总共允许300秒。 暂停可能只在比赛期间进行
。 时间由<<_指令软件操作员, 指令软件操作员>>监视和记录。

NOTE: 例如，一个团队可以有持续60秒的3次暂停，之后只有一次暂停, 持续时间可以长达120秒。

在加时赛期间，两支球队都可以使用2次暂停，总时间为150秒。 不添加暂停次数和常规游戏中未使用的时间。

<<_点球大战, 点球大战>>阶段不可以暂停。

==== 提前结束
当一支球队进球数达到10次时，比赛自动终止，无论目前的比赛阶段如何，有更多进球的球队都被宣布为胜利者。
