== 裁判指令

=== 停止比赛
==== 停止
.定义
当发出停止指令时，所有的机器人必须减速到低于1.5m/s。此外，所有的机器人必须跟球保持至少0.5米的距离，并且不允许进行<<_碰球操作, 碰球操作>>。

NOTE: 如果球运动得很快，一直跟球保持要求的距离是困难的，尤其是在停止时机器人的速度被限制的情况下。因此，如果裁判认为机器人在尽其所能地遵守这条距离规则就足够了。

.使用
停止指令在球越过<<_场地边界线, 场地边界线>>（包括球门）、发生犯规、准备开始比赛、终止比赛后恢复比赛、技术暂停和自动放球的情况下，用于暂停比赛。机器人的速度限制和跟球保持的最小距离允许裁判或者助理裁判没有干扰地安全地放球。

==== 终止
.定义
当发出终止指令时，所有机器人都不允许移动或者进行<<_碰球操作, 碰球操作>>。

这里留有2秒的宽限期给机器人刹车。

.使用
终止指令允许裁判在任何突发事件发生时（例如一个机器人失去控制），立即中断比赛。它也用于在比赛中当图像专家认为有必要和裁判同意时重新校准图像，以及<<_机器人更换, 更换机器人>>。此外，裁判可以按意愿自由地发出终止指令。

终止指令经常伴随着停止指令。

=== 放球
.定义
在比赛停止后，依据发生的事件，球必须被放置在合适的位置。由队伍的机器人完成的没有人工干预的自动放球是把球放在场上指定位置的优先方式。
如果这没能完成，<<_裁判, 裁判>>将人工放球。

球会被认为由机器人成功放置，如果

* 放球指令发出后没有超过30秒
* 如果下一个指令是放球队伍的<<_任意球, 任意球>>，没有机器人在距离球的0.05米范围内
* 如果下一个指令是<<_强制开始, 强制开始>>，没有机器人在距离球的0.5米范围内
* 球是静止的
* 球在距离要求位置的0.15米范围内

<<_比赛指令软件, 比赛指令软件>>不会发出更多的指令，直到自动放球完成。
一旦球被成功放置，且在放球指令发出后不早于2秒，<<_比赛指令软件, 比赛指令软件>>会让比赛继续。
失败的放球会导致对手的一次<<_任意球, 任意球>>。
如果对手也放球失败，球会被<<_裁判, 裁判>>放置，且比赛继续之前的指令。

非放球的队伍不可以<<_干扰放球, 干扰放球>>。

.使用
当出现<<_是否为活球状态的判定, 死球>>时，下列规则决定是否要进行自动放球:

. 开球和点球时，<<_裁判, 裁判>>必须放球
. 对于<<_任意球, 任意球>>，<<Ball In And Out Of Play, 开球>>的队伍必须放球
. 对于<<_强制开始, 强制开始>>，随机决定放球的队伍
. 在放球开始前，球必须可见和不在场地角落、球门角落或者球门后面
. <<_裁判, 裁判>>可以在任何时候决定手动放球
. <<_裁判, 裁判>>可以决定在比赛的剩余时间禁用自动放球。<<_技术委员会, 技术委员会>>必须同意这个决定
. 当一个队伍连续五次放球失败，它将不被允许在比赛半场的剩余时间放球。当球出边线时对手将获得任意球。对于其他违反规则的行为或者当双方队伍都放球失败时，球会被<<Referee, 裁判>>放置
. 如果没有队伍能够放球，球会被<<_裁判, 裁判>>或者<<_助理裁判, 助理裁判>>放置。建议裁判和助理裁判使用放球工具（一个黑色长杆的装置）来放球。

NOTE: 如果球已经在应该放置的位置（例如在另一支队伍失败的任意球后），放球会在没有机器人操纵球的情况下被认为是成功的。这可能会导致在放球队伍没有真正完成一次放球的情况下，放球失败的计数被重置。

NOTE: 当放球指令发出时，球可能仍在运动。

放球对于所有队伍是强制的。如果对手放球失败或者没有队伍能够放球，<<_裁判, 裁判>>或者<<_助理裁判, 助理裁判>>将放球。


=== 恢复比赛
在放球后，比赛将通过以下指令恢复。

==== 标准开始
.定义
这是一个两阶段的裁判指令，当标准开始指令发出时，进攻车可以<<_碰球操作, 碰球操作>>。比赛不能通过标准开始指令直接恢复。

.使用
标准开始指令用于<<_开球, 开球>>、<<_点球,点球判罚>>和<<_点球大战, 点球大战>>。

==== 开球
.定义
球必须被人类裁判放在场地中心。

当发出开球指令时，所有的机器人必须移动到自己的半场，且不在<<_中圈, 中场圆圈>>内。然而，进攻方的一个机器人会被允许进入整个中场圆圈。这个机器人会被认为是开球车。其他机器人不允许碰球。

当<<_标准开球, 标准开球>>指令发出时，开球车被允许踢球。可以直接通过开球进球。

当球处于<<_是否为活球状态的判定, 活球>>状态时，开球车不能碰球直到它被别的机器人碰到或者比赛被停止(参见<<_二次触球, 二次触球>>)。同时，机器人位置的限制被解除。

.使用
半场和加时赛（若有）通过开球开始。<<_比赛准备, 比赛准备>>这一章描述了如何确定进攻方。

另外，在一方进球后，另一方通过开球重新开始比赛。

==== 任意球
.定义
任意球放置的位置取决于导致任意球的事件。如果距离所有<<_场地边界线, 边线>>至少0.2米和距离对方<<_禁区, 禁区>>至少1米，则此位置有效。如果需要将球放置在违反此规则的位置，则必须将其放置在最接近的有效位置。

当发出任意球命令时，允许进攻方的机器人接近球，而防守方的机器人仍然必须与球保持至少0.5米的距离（与停止指令相同的距离）。攻击队的一个机器人被允许踢球，这个机器人将被认为是开球车。任意球可以直接进球得分。

当球处于<<_是否为活球状态的判定, 活球>>状态时，开球车不得触球，直到球被其他机器人触碰或者比赛已经停止（见<<_二次触球, 二次触球>>）。此外，对于机器人位置的限制将被解除。

.使用
在<<_犯规, 犯规>>发生后，任意球被用来重新开始比赛。此外，<<_球门球, 球门球>>和<<_角球, 角球>>被认为是任意球。

==== 强制开始
.定义
当发出强制开始指令时，游戏立即恢复，并且允许两个队伍再次接近并执行<<_碰球操作, 碰球操作>>。

.使用
如果在两队都被允许接近并执行<<碰球操作, 碰球操作>>的情况下至少10秒没有明显的进展，裁判可以发出一个停止命令，然后强制开始。

当比赛必须停止并且没有队伍或两个队伍都有过错时，它也可用于恢复游戏。

==== 点球
//新定义根据2023年规则 --mark 1/4/2023
.定义
点球判罚的完整流程如下：

. 发起一颗点球，首先发出停止指令并由<<_裁判, 裁判>>将球放在<<_点球点, 点球点>>上。
. 当发出点球指令时：
.. 防守方守门员必须移动到球门线上并保持接触。
.. 一个进攻方机器人允许接近球但不能碰球。
. 整个点球过程中，所有其他机器人需要保持在球后方一米的位置以保证不会影响整个点球流程。
. 当<<_标准开始, 标准开始>>指令发出后，进攻方机器人允许进行<<_碰球操作, 碰球操作>>。需要注意的是，球只被允许朝向敌方球门的方向移动，该条规则将根据<<_共享视觉系统, 共享视觉系统软件>>中球的x坐标值进行判断。
. 当球进入<<_是否为活球状态的判定, 活球>>状态时，防守方守门员可以进行自由移动。
. 如果10秒后球依然处于<<_是否为活球状态的判定, 活球>>状态，则比赛<<_停止, 暂停>>。

当满足以下任意条件时，进球被视作有效：

. 当<<_标准开始, 标准开始>>指令发出后，球接触到了防守方球门的内侧边或地面。
. 防守方出现任何<<_犯规, 犯规>>。

若视为有效进球，则以<<_开球, 开球>>指令继续比赛。

当满足以下任意条件时，进球被视作无效：

. 球穿过任何球门以外的<<_场地边界线, 边界线>>。
. 防守方守门员碰球引起的球速方向在2D空间下变化超过90度。
. 进攻方出现任何<<_违规行为, 违规行为>>（在点球进程中，<<_二次触球, 二次触球>>不会被视作<<_违规行为, 违规行为>>）。
. 超过10秒后球仍然处于<<_是否为活球状态的判定, 活球>>状态。

当点球没有造成有效进球后，将以<<_球门球, 球门球>>指令继续比赛。

NOTE: 在<<_进球, 有效进球>>的定义中，0.15m的高度限制不适用于点球判罚。其他限制如<<_带球过度, 带球过度>>等同样适用于点球判罚。

在每个半场或某比赛阶段结束时，允许有额外的时间执行点球判罚。

.使用
点球判罚被用来惩罚<<_违反体育精神的行为, 违反体育精神的行为>>和<<_非守门员禁区触球, 非守门员禁区触球>>。

=== 是否为活球状态的判定

当比赛为<<_停止比赛, 停止>>状态，直到下一次比赛开始之前均被认定为死球状态。

当比赛<<_恢复比赛, 恢复>>，直到下一次需要停止的事件发生之前均为活球状态。当出现以下任意情况时，比赛恢复即进入活球状态：

. 当<<_强制开球, 强制开球>>指令下发。
. 在<<_开球, 开球>>、<<_任意球, 任意球>>或<<_点球, 点球>>状态下球移动超过0.05m。
. 在<<_开球, 开球>>指令下发10秒以后。
. 在<<_任意球, 任意球>>指令下发5秒以后。

NOTE: 关于0.05m距离的规则请参考<<_二次触球, 二次触球>>

=== 判罚

==== 黄牌
.定义

如果黄牌是<<_违反体育精神的行为, 违反体育精神的行为>>导致的结果，则裁判可以决定立即<<Halt, 终止>>比赛。在这种情况下，另一支球队将获得任意球。

收到黄牌后，受罚球队场上允许的机器人数量减少一个。如果在减少之后，队伍拥有的机器人数量超过现场允许的数量，则必须在<<Resuming The Game, 恢复比赛>>前<<Robot Substitution, 拿走>>机器人。受惩罚的团队可以选择要移除的机器人。

当队伍在场机器人数量超过允许数量时，进球无效。

在120秒的比赛时间（由比赛指令软件测量）后，黄牌到期并且允许的机器人的数量将增加1。队伍可以在下一次可能的时候<<_机器人更换, 放入机器人>>。

当一个队伍在有两张黄牌生效的时候再次获得一张黄牌，这张黄牌将直接变为红牌。

.使用
黄牌被用于惩罚多次<<_违规行为, 违规>>的球队。

裁判员也可以给出黄牌以惩罚<<_违规行为, 违规>>或<<_违反体育精神的行为, 违反体育精神的行为>>。

==== 红牌
.定义
红牌与<<_黄牌, 黄牌>>相似，不同之处在于它直到比赛结束才到期。

.使用
裁判员会给出红牌，以惩罚严重的<<_违规行为, 违规>>或<<_违反体育精神的行为, 违反体育精神的行为>>。

NOTE: 例如，机器人的严重暴力接触或对裁判的不尊重行为可能导致红牌。


==== 强制弃赛
.定义
强制弃赛意味着一支球队立即以0比10的分数输掉当前比赛。

.使用
如果团队无法提供至少一个满足规则的机器人进行比赛，则可能被强制弃赛。

只有在与<<_技术委员会, 技术委员会>>成员达成协议的情况下，队伍才能被强制弃赛。

==== 取消比赛资格
.定义
取消资格意味着一支球队立即结束所有比赛并排在最后。该队伍没有资格获得任何奖杯。

.使用
如果该团队的成员不遵守安全准则，场地规则或几次犯相似的严重违规行为，则队伍可能被取消资格。

只有在与<<_技术委员会, 技术委员会>>成员达成协议的情况下，队伍才能被取消资格。