== 违规行为
根据犯规的严重程度，犯规被分为以下几种：<<_违例, 违例>>、<<_犯规, 犯规>>和<<_违反体育精神的行为,违反体育精神的行为>>。

NOTE: 违例一般是指<<_是否为活球状态的判定, 活球状态>>时进攻机器人的违规行为，犯规一般是指防守机器人的违规行为、比赛中断时的违规行为以及对人、机器人或场地造成损害的违规行为。

=== 僵持状态
僵持状态是指在比赛进行中超过5秒没有任何进展，即在两球队都处于允许<<_碰球操作, 碰球操作>>的状态下，球处于僵持不动。此时比赛会进入<<_停止, 停止>>状态后再衔接<<_强制开始, 强制开始>>指令。

=== 违例
比赛中，一方发生违例行为后，比赛中断，并在违例发生的地方判给对方一粒<<_间接任意球, 间接任意球>>（具体开球位置参见<<_直接任意球, 直接任意球>>）。所有违例行为如下：

==== 超时
以下行为会被视为超时：

* 未在5秒内开出<<_直接任意球, 直接任意球>>或<<_间接任意球, 间接任意球>>；
* 未在10秒内完成<<_开球, 开球>>或<<_点球, 点球>>的；
* 守门员未在10秒内将球清出己方<<_禁区, 禁区>>的。

NOTE: 如果比赛处于双方允许进行<<_碰球操作, 碰球操作>>的状态，且两队均未违例，<<_裁判, 裁判>>可以停止比赛并发出<<_强制开始, 强制开始>>的指令。

NOTE: 如果比赛双方都无法在不违规的情况下使比赛进入<<_是否为活球状态的判定, 活球>>状态，<<_裁判, 裁判>>可以用<<_强制开始, 强制开始>>指令代替另一方的<<_间接任意球, 间接任意球>>指令。

==== 二次触球
开球机器人完成<<_开球, 开球>>、<<_直接任意球, 直接任意球>>、<<_间接任意球, 间接任意球>>或<<_点球, 点球>>使比赛开始后，在其他机器人触碰球之前再次触碰球的行为被视为二次触球。

球在移动超过0.05米之后被视为比赛开始。

NOTE: 机器人踢球时，难免会与球发生多次碰撞，这也是用0.05米的距离来确定机器人是否犯规的原因。即使球与机器人只发生过一次接触，开球时持球移动超过0.05米也被视为二次触球。

==== 对方禁区内触球
当机器人位于或部分位于对方的<<_禁区, 禁区>>时不允许触球。

NOTE: 当比赛处于<<_是否为活球状态的判定, 死球>>状态下，需要遵守更严格的规则：<<_机器人到对方禁区距离过短, 机器人到对方禁区距离过短>>。

==== 带球过度
机器人从触球的位置算起，<<_运球装置, 带球>>距离不能超过一米。机器人与球接触被视为带球开始，机器人与球之间存在可见分离被视为带球结束。

NOTE: 像人类足球运动员前踢带球那样，只要机器人可以周期性的失去对球的控制，那么机器人带球是符合规则的。

==== 球速过快
在三维空间内，机器人不能使球速超过6.5米/秒。

=== 犯规
比赛中，一方发生犯规行为后，比赛中断，并在犯规发生的地方判给对方一粒<<_直接任意球, 直接任意球>>（具体开球位置参见<<_直接任意球, 直接任意球>>）。当犯规发生在<<_是否为活球状态的判定, 非活球>>的情况下，不会判罚任意球。

同一支队伍每三次犯规将被判一张<<_黄牌, 黄牌>>。<<_裁判, 裁判>>也可以根据犯规的严重程度判罚<<_黄牌, 黄牌>>或<<_红牌, 红牌>>。

所有犯规行为如下：

==== 机器人在对方禁区触碰对方机器人
当比赛处于<<_是否为活球状态的判定, 活球>>状态时，机器人不能触碰敌方<<_禁区, 禁区>>内任何敌方机器人。

NOTE: 当比赛处于<<_是否为活球状态的判定, 死球>>状态时，遵循<<_机器人到对方禁区距离过短, 机器人到对方禁区距离过短>>。

==== 机器人到对方禁区距离过短

在比赛处于<<_停止, 停止>>、<<_直接任意球, 直接任意球>>或<<_间接任意球, 间接任意球>>的状态时，所有机器人必须与对方<<_禁区, 禁区>>保持至少0.2米的距离。对于已经处在<<_禁区, 禁区>>内的机器人，需要在2秒内离开。

==== 干扰放球
在比赛处于<<_放球, 自动放球>>状态时，非放球队伍的所有机器人必须与球与放置位置之间的连线保持至少0.5米的距离（该区域形状类似于胶囊），对于已经处在该区域内的机器人，需要在2秒内离开，否则记一次犯规并重置放球过程。

NOTE: 规则中没有包含所有的干扰放球的行为，所以在非放球队伍有明显的干扰放球行为时，<<_裁判, 裁判>>可以记该队一次犯规。

==== 碰撞
当两个不同队伍的机器人发生碰撞时，记录两个机器人速度矢量在二者连线投影上的差值，如果投影值大于1.5米/秒，速度较大的机器人所在队伍记一次犯规，如果速度的绝对值的差小于0.3米/秒，则双方各记一次犯规，比赛不中断。

==== 推挤
当双方机器人都与球接触或者彼此接触时，机器人施力使对方机器人在自己朝向移动，这种行为被视为推挤。

NOTE: 当双方机器人都用近似的力推挤对方机器人时，双方都不犯规。

==== 护球
机器人不能将球包裹以至于对方机器人无法拿到球。

==== 翻倒或掉落零件
机器人不得翻倒，爆炸或在场地上掉落对其他机器人有潜在威胁的零件。犯规机器人必须被<<替补, 替换>>。

NOTE: 金属部件（例如螺钉）以及较大的部件通常构成潜在的威胁，非常小的非金属部件（例如橡胶圈）不会构成威胁。

==== 停止状态机器人速度
在停止的状态下机器人车速不能超过1.5米/秒，对于已超速的，需要在2秒内减速。同样的犯规每机器人每状态只记一次。

NOTE: 该规则不适用于<<放球, 放球>>状态。

NOTE: 由于停止命令是用于手动放球和机器人<<替补,替换>>的，限制机器人速度是为了避免机器人伤到场上人员。

==== 机器人离球过近
在对方进行<<开球, 开球>>、<<直接任意球, 直接任意球>>或<<间接任意球, 间接任意球>>时，机器人必须与球保持至少0.5米的距离。犯规后，比赛指令保持与犯规前一致。

NOTE: 在<<停止, 停止>>状态下，不会自动判定机器人与球的距离，但<<裁判, 裁判>>可以<<违反体育精神的行为, 违反体育精神的行为>>对不遵守要求距离的队伍一张<<黄牌,黄牌>>。详细参见<<停止, 停止状态>>。

==== 非守门员禁区触球

NOTE: <<_犯规, 犯规>>定义下的判罚不适用于该规则。

如果非守门员机器人在部分进入己方禁区的情况下触球，比赛停止，记一张<<_黄牌,黄牌>>，判给对方一粒<<_直接任意球, 直接任意球>>，犯规次数不增加。

如果非守门员机器人在完全进入己方禁区的情况下触球，比赛停止，判给对方一次<<_点球, 点球罚球>>，犯规次数不增加。

=== 违反体育精神的行为
针对违反体育精神的行为，<<_裁判, 裁判>>可以根据犯规的严重程度给予<<_黄牌, 黄牌>>、<<_红牌, 红牌>>、<<_点球, 点球>>、<<_强制弃赛, 强制弃赛>>或<<_取消比赛资格, 取消比赛资格>>的处罚。人工裁判可以根据违规的严重程度选择合适的处罚。

对于请为的犯规，<<_黄牌, 黄牌>>就足够了，而对于更严重的犯规，给球队带来了优势，可以判罚<<_红牌, 红牌>>或者<<_点球, 点球>>。

对于更严厉的处罚，建议裁判员咨询<<_技术委员会, 技术委员会>>成员。

NOTE: 如果裁判员不确定如何判罚，可以与<<_助理裁判, 助理裁判>>和 <<_技术委员会, 技术委员会>> 成员协商。

下面列出了一些违反体育精神行为示例。

==== 破坏其他机器人
比赛队伍不允许破坏或改装其他队伍的机器人。

==== 破坏场地或比赛用球
比赛队伍不允许破坏或改变场地或比赛用球。

==== 不尊重比赛进程
没有遵循比赛进程的行为例如：

* <<_团队负责人, 团队负责人>>在不被允许的情况下将机器人放置场地内
* 机器人在停止时没有与球保持应需的距离
* 机器人在<<_点球, 点球>>判罚时未移动到规定位置，需要手动搬运或移除

==== 不尊重比赛
团队成员必须对参与比赛的每一个人表现出适当的尊重。违反本规则的行为包括但不限于：

* 侮辱对手、<<_裁判, 裁判>>或其他担任<<公正角色, 公正角色>>的人
* 激怒<<_裁判, 裁判>>或其他担任<<公正角色, 公正角色>> 的人
* 不遵守<<_裁判, 裁判>>的指令

=== 同时犯规
如果比赛<<_停止, 暂停>>并且一个队伍被允许<<_恢复比赛, 恢复比赛>> ，对手的<<_违例, 违例>>和<<_犯规, 犯规>>不会影响比赛重新开始的方法与位置，除非对手被判罚<<_点球, 点球>>。

如果一个队伍利用了这个规则，<<_裁判, 裁判>>可以记该队一张<<_黄牌, 黄牌>>来惩罚该队伍的<<_违反体育精神的行为, 违反体育精神的行为>>。

NOTE: 该规则旨在防止队伍故意犯规，以便将对手的<<_直接任意球, 直接任意球>>或<<_间接任意球, 间接任意球>>重新定位到更有利的位置。

=== 有利规则
在某些情况下，由于犯规而停止比赛可能对对方不利。
由于这些情况不容易自动检测到，因此会询问对方是否选择继续比赛。
在这种情况下，游戏不会停止，也不会判罚任意球。
当比赛<<_停止, 暂停>>时，犯规计数器仍然递增，并仍会给出红黄牌。

以下情况被视为符合上述条件：

* 单个队伍的<<_碰撞, 碰撞>>犯规；
* <<_机器人在对方禁区触碰对方机器人, 机器人在对方禁区触碰对方机器人>>。

NOTE: 如果队伍没有连接到游戏控制器或在0.2秒内没有回复，则队伍的决定默认为停止游戏。
