== 违规行为

=== 僵持状态
僵持状态是指在比赛进行中超过5秒没有任何进展，即在两球队都处于允许<<_碰球操作, 碰球操作>>的状态下，球处于僵持不动。此时比赛会进入<<_停止, 停止>>状态后再衔接<<_强制开始, 强制开始>>指令。

=== 二次触球
开球机器人完成<<_开球, 开球>>、<<_任意球, 任意球>>或<<_点球, 点球>>使比赛开始后，在其他机器人触碰球或比赛暂停之前再次触碰球的行为被视为二次触球。

球在移动超过0.05米之后被视为比赛开始。

NOTE: 机器人踢球时，难免会与球发生多次碰撞，这也是用0.05米的距离来确定机器人是否犯规的原因。即使球与机器人只发生过一次接触，开球时持球移动超过0.05米也被视为二次触球。

二次触球发生后比赛进入到<<_停止, 停止>>状态，随后在犯规位置判罚一颗

=== 犯规
// 比赛中，一方发生犯规行为后，比赛中断，并在犯规发生的地方判给对方一粒<<_任意球, 任意球>>（具体开球位置参见<<_任意球, 任意球>>）。当犯规发生在<<_是否为活球状态的判定, 非活球>>的情况下，不会判罚任意球。

同一支队伍每三次犯规将被判一张<<_黄牌, 黄牌>>。<<_裁判, 裁判>>也可以根据犯规的严重程度判罚<<_黄牌, 黄牌>>或<<_红牌, 红牌>>。

==== 导致比赛暂停的犯规

以下犯规会导致比赛进入<<_停止, 暂停>>状态，随后在犯规发生位置判罚一个对手的<<_任意球, 任意球>>。

===== 机器人到对方禁区距离过短
在比赛处于<<_停止, 停止>>、<<_任意球, 任意球>>的状态时，所有机器人必须与对方<<_禁区, 禁区>>保持至少0.2米的距离。对于已经处在<<_禁区, 禁区>>内的机器人，需要在2秒内离开。

===== 推挤
当双方机器人都与球接触或者彼此接触时，机器人施力使对方机器人在自己朝向移动，这种行为被视为推挤。

NOTE: 当双方机器人都用近似的力推挤对方机器人时，双方都不犯规。

===== 护球
机器人不能将球包裹以至于对方机器人无法拿到球。

===== 翻倒或掉落零件
机器人不得翻倒，爆炸或在场地上掉落对其他机器人有潜在威胁的零件。犯规机器人必须被<<替补, 替换>>。

NOTE: 金属部件（例如螺钉）以及较大的部件通常构成潜在的威胁，非常小的非金属部件（例如橡胶圈）不会构成威胁。

===== 非守门员禁区触球

NOTE: <<_犯规, 犯规>>定义下的判罚不适用于该规则。

除守门员外，机器人必须尽最大努力保持在自身禁区之外。违反此规则可被视为<<_违反体育精神的行为, 违反体育精神的行为>>。

如果非守门员机器人在完全进入己方禁区的情况下触球，比赛停止，判给对方一次<<_点球, 点球罚球>>，犯规次数不增加。

===== 将球踢出边界
机器人不得将球踢出边界导致球离开场地。

===== 守门员持球过久
球在己方<<_禁区, 禁区>>持续时间不得超过10秒。

===== 带球过度
机器人从触球的位置算起，<<_运球装置, 带球>>距离不能超过一米。机器人与球接触被视为带球开始，机器人与球之间存在可见分离被视为带球结束。

NOTE: 像人类足球运动员前踢带球那样，只要机器人可以周期性的失去对球的控制，那么机器人带球是符合规则的。

==== 不会导致比赛暂停的犯规

以下犯规不会导致比赛进入<<_停止, 暂停>>状态，比赛会继续正常进行。

在<<_犯规, 犯规>>行为未停止或者距离<<_犯规, 犯规>>行为触发未超过2秒，该<<_犯规, 犯规>>行为不会再次被记录。这样做是为了让球队有机会调整机器人的位置、球速或任何其他导致违规的因素来防止多次被处罚。

===== 对方禁区内触球
当机器人位于或部分位于对方的<<_禁区, 禁区>>时不允许触球。

NOTE: 当比赛处于<<_是否为活球状态的判定, 死球>>状态下，需要遵守更严格的规则：<<_机器人到对方禁区距离过短, 机器人到对方禁区距离过短>>。

===== 球速过快
在三维空间内，机器人不能使球速超过6.5米/秒。

===== 碰撞
当两个不同队伍的机器人发生碰撞时，记录两个机器人速度矢量在二者连线投影上的差值，如果投影值大于1.5米/秒，速度较大的机器人所在队伍记一次犯规，如果速度的绝对值的差小于0.3米/秒，则双方各记一次犯规，比赛不中断。

==== 非活球状态下的犯规
以下犯规只能在<<_是否为活球状态的判定, 非活球>>状态下发生。

每队每次犯规都会有2秒的宽限期，之后会再次受到处罚。

NOTE: 如果多个机器人在2秒内触发相同犯规，只有第一次犯规作数。

===== 机器人离球过近
在对方进行<<开球, 开球>>、<<任意球, 任意球>>时，机器人必须与球保持至少0.5米的距离。犯规后，比赛指令保持与犯规前一致。

NOTE: 在<<停止, 停止>>状态下，不会自动判定机器人与球的距离，但<<裁判, 裁判>>可以<<违反体育精神的行为, 违反体育精神的行为>>对不遵守要求距离的队伍一张<<黄牌,黄牌>>。详细参见<<停止, 停止状态>>。

===== 停止状态机器人速度
在停止的状态下机器人车速不能超过1.5米/秒，对于已超速的，需要在2秒内减速。同样的犯规每机器人每状态只记一次。

NOTE: 该规则不适用于<<放球, 放球>>状态。

NOTE: 由于停止命令是用于手动放球和机器人<<替补,替换>>的，限制机器人速度是为了避免机器人伤到场上人员。

===== 干扰放球
在比赛处于<<_放球, 自动放球>>状态时，非放球队伍的所有机器人必须与球与放置位置之间的连线保持至少0.5米的距离（该区域形状类似于胶囊），对于已经处在该区域内的机器人，需要在2秒内离开，否则记一次犯规并重置放球过程。

NOTE: 规则中没有包含所有的干扰放球的行为，所以在非放球队伍有明显的干扰放球行为时，<<_裁判, 裁判>>可以记该队一次犯规。


=== 违反体育精神的行为
针对违反体育精神的行为，<<_裁判, 裁判>>可以根据犯规的严重程度给予<<_黄牌, 黄牌>>、<<_红牌, 红牌>>、<<_点球, 点球>>、<<_强制弃赛, 强制弃赛>>或<<_取消比赛资格, 取消比赛资格>>的处罚。人工裁判可以根据违规的严重程度选择合适的处罚。

对于轻微的犯规，<<_黄牌, 黄牌>>就足够了，而对于更严重的犯规，给球队带来了优势，可以判罚<<_红牌, 红牌>>或者<<_点球, 点球>>。

对于更严厉的处罚，建议裁判员咨询<<_技术委员会, 技术委员会>>成员。

NOTE: 如果裁判员不确定如何判罚，可以与<<_助理裁判, 助理裁判>>和 <<_技术委员会, 技术委员会>> 成员协商。

下面列出了一些违反体育精神行为示例。

==== 破坏其他机器人
比赛队伍不允许破坏或改装其他队伍的机器人。

==== 破坏场地或比赛用球
比赛队伍不允许破坏或改变场地或比赛用球。

==== 不尊重比赛进程
没有遵循比赛进程的行为例如：

* <<_团队负责人, 团队负责人>>在不被允许的情况下将机器人放置场地内
* 机器人在停止时没有与球保持应需的距离
* 机器人在<<_点球, 点球>>判罚时未移动到规定位置，需要手动搬运或移除

==== 不尊重比赛
团队成员必须对参与比赛的每一个人表现出适当的尊重。违反本规则的行为包括但不限于：

* 侮辱对手、<<_裁判, 裁判>>或其他担任<<公正角色, 公正角色>>的人
* 激怒<<_裁判, 裁判>>或其他担任<<公正角色, 公正角色>> 的人
* 不遵守<<_裁判, 裁判>>的指令