== 比赛体系
=== 公正的角色
要在小型组中进行正式比赛，必须满足四个公正的角色：

* <<Referee, referee>>
* <<Assistant Referee, assistant referee>>
* <<Game Controller Operator, game controller operator>>
* <<Vision Expert, vision expert>>

通常，这些角色由两个非参赛队伍担任，其中一个队伍提供<<Referee, referee>>和<<Game Controller Operator, game controller operator>>，另一个团队提供 <<Assistant Referee, assistant referee>> 和<<Vision Expert, vision expert>>。 角色的分配由<<Organizing Committee, organizing committee>>决定。每个参赛团队的成员都必须熟悉这些人员。

==== 裁判
每场比赛由裁判控制。他完全有权执行小型组比赛相关的规则。建议裁判使用场地旁边的指定步行区域（参见<<Field Setup>>）。

裁判由<<Automatic Referee, automatic referee>>软件协助。允许裁判覆盖裁判软件做出的任何决定。

裁判关于与比赛有关的裁决是最终的。裁判只能改变自己认为不正确的决定，或者由他自行决定更改助理裁判的建议，但他不能重新开始比赛。

裁判员不对任何官员或旁观者遭受的任何伤害，任何形式的财产损失或个人，俱乐部，公司，协会或其他机构遭受的任何其他损失承担责任。

<<Robot Handler, robot handler>> 是唯一的可以与裁判交谈的团队成员。

.任务

* 裁判为所有的人和机器人确保了一个安全的比赛
* 裁判根据小型组的规则确保了一个相对公平的比赛
* 裁判确保未经授权的人员或团队成员不会干涉比赛
* 裁判或助理裁判将球置于<<Kick-Off, kick-offs>> 和 <<Penalty Kick, penalties>>（A组）或每次<<Stopping The Game, stoppage>>（B组）之后。 随后，裁判恢复比赛
* 裁判确保比赛开始并及时恢复

==== 助理裁判
助理裁判在任何可能的地方支持裁判。并且被鼓励使用在裁判员对面的 <<Field Setup, field>> 旁边的指定步行区。

参赛队伍的成员不被允许与助理裁判交谈

.任务

* 当发生的一些不当行为或任何其他事件在裁判视野之外时,助理裁判应当指出
* 助理裁判与裁判讨论不能清楚裁决的情况
* 裁判或助理裁判将球置于<<Kick-Off, kick-offs>> and <<Penalty Kick, penalties>>（A组）或每次<<Stopping The Game, stoppage>>之后（B组）


==== Game Controller Operator
在比赛期间，Game Controller Operator使用<<Game Controller, game controller software>>作为he <<Referee, referee>>, the <<Automatic Referee, automatic referee>>和团队软件之间的接口。

参赛队伍的成员不允许与Game Controller Operator交谈,除非发生 <<Robot Handler, robot handler>> 和 <<Robot Substitution, robot substitution>>的情况。

.任务
* Game Controller Operator在比赛开始之前配置 <<Game Controller, game controller>>
* Game Controller Operator将<<Referee, referee>>的信号输入到<<Game Controller, game controller>>中
* Game Controller Operator在比赛事件日志中查看需要注意的事件，例如<<Automatic Referee, automatic referee>>或经过的计时器的检测，并通知<<Referee, referee>>

==== Vision Expert
在比赛期间，Vision Expert负责该领域的<<Vision, shared vision system>>。

通常建议团队成员不要与Vision Expert交谈，除非他们遇到重大视觉方面的问题。

.任务
* Vision Expert检查视觉硬件并向<<Technical Committee, technical committee>>报告任何类型的硬件问题
* 视觉专家在比赛期间监控共享视觉系统，并立即向裁判报告任何类型的问题
* 如果裁判认为有必要，视觉专家会重新校准视觉系统

=== 团队特定角色

==== Robot Handler
在比赛开始之前，每个团队都必须指定一个Robot Handler。Robot Handler在比赛期间代表该团队比赛。

.任务
* Robot Handler有助于<<Match Preparation, preparing the match>>。
* 如有必要，Robot Handler会要求裁判<<Timeouts, timeouts>>。
* Robot Handler要求裁判在下一次停止时取代机器人，如果裁判同意，则<<Robot Substitution, substitutes the robot>>。
* Robot Handler反映团队比较关心的问题（例如网络问题或视觉问题）。

=== 比赛准备
所有在比赛中发挥作用的人（<<Impartial Roles, impartial>> 或者 <<Team-Specific Roles, team-specific>>）必须在比赛开始前至少10分钟做好以下准备：

==== 比赛结果表
<<Referee, referee>>从<<Organizing Committee, organizing committee>>获得比赛结果表。 比赛结束后，裁判填写最终比分，收集所需签名，并将表格提交给 <<Organizing Committee, organizing committee>>。

NOTE: 在获得比赛结果表时，裁判还可以使用官方的 <<Ball, ball>>和裁判设备，如哨子或红牌和黄牌（如果提供的话）。

==== 测试网络
<<Referee, referee>> 确保两支球队都能获得视觉数据和裁判命令。

==== 选择团队颜色
<<Referee, referee>>询问球队的 <<Robot Handler, robot handlers>> ，了解他们更喜欢的球队颜色（蓝色或黄色）。 如果团队同意颜色分配，颜色将用于整个比赛。

但是，如果两队都喜欢相同的颜色，裁判会随机分配颜色。 在这种情况下，球队在比赛的前半段之后以及加时赛的前半段之后切换颜色（如果适用）。

==== 选择半场和开球
<<Referee, referee>> 用<<Robot Handler, robot handlers>>投掷硬币。 获胜队将在比赛的前半段选择进攻的目标。 另一支球队<<Kick-Off, kick-off>> 以开始比赛。

==== 选择守门员ID
<<Referee, referee>> 询问 <<Robot Handler, robot handlers>> 他们将使用哪个机器人作为守门员，并将此信息转发给<<Game Controller Operator, game controller operator>>。

NOTE: 如果团队不想使用守门员，则可以选择不在场上的机器人的ID。

=== 比赛阶段
==== 概述
小型组的官方比赛包括以下几个阶段：

|===
| 比赛阶段 | 时长

| 上半场 | 比赛时间 300 秒
| 中场休息 | 暂停 300 秒
| 下半场 | 比赛时间 300 秒
|===

如果比赛是淘汰赛（比赛结果不可以是平局），并且在正常比赛时间之后比分相同，比赛将进入加时赛，并添加以下比赛阶段：

|===
| 比赛阶段 | 时长

| 加时赛前休息 | 暂停 300 秒
| 加时赛上半场 | 比赛时间 150 秒
| 加时赛中场休息 | 暂停 120 秒
| 加时赛下半场 | 比赛时间 150 秒
|===

如果加时赛后双方比分仍相等, 则添加以下比赛阶段:

|===
| 比赛阶段 | 时长

| Shoot-Out前休息 | 暂停 120 秒
| <<Shoot-Out>> | 无限制时长
|===

只要没有球队被允许进行<<Ball Manipulation, manipulate the ball>>，比赛计时器就会暂停。 这包括<<Stop, stop>>，<<Halt, halt>>以及<<Kick-Off, kick-off>>和<<Penalty Kick, penalty kick>>的准备状态。 此外，它在<<Ball Placement, ball placement>>期间暂停。

NOTE: 因此，比赛所需的时间远远大于比赛时间。

==== 暂停
<<Robot Handler, robot handler>> 必须要求裁判暂停。 暂停的处理方式类似于<<Overview, breaks>>，这意味着允许两个团队对其软件和硬件进行修改（参见<<Autonomy>>）。

每支球队在比赛开始时分配4次暂停。 所有暂停总共允许300秒。 暂停可能只在比赛期间进行
。 时间由<<Game Controller Operator, game controller operator>>监视和记录。

NOTE: 例如，一个团队可以有持续60秒的3次暂停，之后只有一次暂停, 持续时间可以长达120秒。

在加时赛期间，两支球队都可以使用2次暂停，总时间为150秒。 不添加暂停次数和常规游戏中未使用的时间。

<<Shoot-Out, shoot-out>> 阶段不可能暂停。

==== 提前结束
当一支球队进球10次时，比赛自动终止，无论目前的比赛阶段如何，有更多进球的球队都被宣布为胜利者。
