== 组别概述
=== 委员会
小型组 (如同其他的RoboCup组别一样) 是依靠密切合作的三个委员会来运转的 (<<执行委员会(EC), 执行委员会(EC)>>, <<技术委员会(TC), 技术委员会(TC)>> 和 <<组织委员会(OC), 组织委员会(OC)>>), 三个委员会各有不同的职责。 各个委员会的成员可以在RoboCup小型组的官网上找到(https://ssl.robocup.org)。

NOTE: 实际上，对于 <<技术委员会(TC), TC>> 和 <<组织委员会(OC), OC>>并没有严格的区分。成员们通常会一起讨论完成一系列任务。

另外，<<当地组织委员会(LOC), 当地组织委员会(LOC)>> 的成员负责组织RoboCup所有的组别。

==== 执行委员会(EC)
执行委员会的成员有义务负责小型组的长期目标，所以成员童谣需要与包括RoboCup联盟在内的其他组别进行联系。执行委员会每年负责向RoboCup联盟展示小型组取得的成就并且依据反馈来组织小型组。执行委员会的成员由RoboCup联盟的董事会直接选举。

==== 技术委员会(TC)
技术委员会负责小型组技术方面，例如维持规则以及<<共享软件,共享软件(shared software)>> 。所有技术委员会成员由前一年的比赛参与队伍推选。

==== 组织委员会(OC)
组织委员会负责比赛的组织及准备，只要包括制定比赛日程、执行评审过程以及比赛运转。成员由<<执行委员会(EC), 执行委员会>>的RoboCup的受托人直接任命。

==== 当地组织委员会(LOC)
当地组织委员会负责依照不同组别的需要计划和执行赛事本身。这包括布置队伍区域（team area），包括场地、网络、桌椅、白板以及显示屏等，同时需要创建一个日程表并落实安全保障理念。

=== 组别(Division)
小型组分成了两个赛制的比赛分别叫组别A(Division A)和组别B(Division B)。组别A是针对一些相对先进的队伍的而新的队伍以及其他缺乏竞争力的队伍可以参与组别B的比赛。每个队伍只能在两个组别中选择一个参加。

当提交审核材料的时候，队伍可以选择自己偏好的组别同时阐述一个简短的理由。<<组织委员会(OC), OC>>成员将具有队伍组别的最终决定权。关于审核进程的相关信息可以在RoboCup小型组官网上找到(https://ssl.robocup.org) 。

关于两个组别不同的更多信息请参考 <<Differences Between Divisions, 附录>>。

NOTE: 组别的分离保证了在不提高新队伍的入门门槛的同时使得小型组可以有更快速的进步。同时，这也提高了相近水平队伍之间的比赛次数。