== 违规行为
根据犯规的严重程度，犯规被分为以下几种：<<违例, 违例>>、<<犯规, 犯规>>和<<违反体育精神的行为,违反体育精神的行为>>。

NOTE: 违例一般是指比赛进行时进攻机器人的违规行为，犯规一般是指防守机器人的违规行为、比赛中断时的违规行为以及对人、机器人或场地造成损害的违规行为。

=== 违例
比赛中，一方发生违例行为后，比赛中断，并在违例发生的地方判给对方一粒<<间接任意球, 间接任意球>>（具体开球位置参见<<直接任意球, 直接任意球>>）。所有违例行为如下：

==== 无意义射门 [small]#(_B组_)#
满足以下全部条件的行为会被视为无意义射门：

* 球越过中线；
* 球在对方底线出界；
* 对方机器人未触球。

开球不会被视为无意义射门，因为开球位置在中线上，所以球不会越过中线。

==== 超时
以下行为会被视为超时：

* 未在5秒内开出<<直接任意球, 直接任意球>>或<<间接任意球, 间接任意球>>的（B组为10秒）；
* 未在10秒内完成<<开球, 开球>>或<<点球, 点球>>的；
* 守门员未在10秒内将球清出己方禁区的。

NOTE: 如果比赛双方均可控球，则两队均未违例，裁判可以停止比赛并发出<<强制开始, 强制开始>>的指令。

NOTE: 如果比赛双方都无法在不违规的情况下使比赛开始，裁判可以用<<强制开始, 强制开始>>指令代替另一方的<<间接任意球, 间接任意球>>指令。

==== 二次触球
开球机器人完成<<开球, 开球>>、<<直接任意球, 直接任意球>>、<<间接任意球, 间接任意球>>或<<点球, 点球>>使比赛开始后，在对方机器人触碰球之前再次触碰球的行为被视为二次触球。

球在移动超过0.05米之后被视为比赛开始。

NOTE: 机器人踢球时，难免会与球发生多次碰撞，这也是用0.05米的距离来确定机器人是否犯规的原因。即使球与机器人只发生过一次接触，开球时持球移动超过0.05米也被视为二次触球。

==== 对方禁区内触球
当机器人位于或部分位于对方的<<禁区, 禁区>>时不允许触球。

NOTE: 当<<比赛中断, 比赛中断>>时，需要遵守更严格的规则：<<机器人到对方禁区距离过短,机器人到对方禁区距离过短>>。

==== 带球过度
机器人从触球的位置算起，<<带球, 带球>>距离不能超过一米。机器人与球接触被视为带球开始，机器人与球之间存在可见分离被视为带球结束。

NOTE: 像人类足球运动员前踢带球那样，只要机器人可以周期性的失去对球的控制，那么机器人带球是符合规则的。

==== 球速过快
在三维空间内，机器人不能使球速超过6.5米/秒。

=== 犯规
比赛中，一方发生犯规行为后，比赛中断，并在犯规发生的地方判给对方一粒<<直接任意球, 直接任意球>>（具体开球位置参见<<直接任意球, 直接任意球>>）。当犯规发生在比赛中断的情况下，不会判罚任意球。

同一支队伍每三次犯规将被判一张黄牌。裁判也可以根据犯规的严重程度判罚<<黄牌, 黄牌>>或<<红牌, 红牌>>。

所有犯规行为如下：

==== 机器人在对方禁区触碰对方机器人
当比赛进行时，机器人不能触碰对方禁区内对方的任何机器人。

==== 机器人到对方禁区距离过短

在比赛处于<<停止, 停止>>、<<直接任意球, 直接任意球>>或<<间接任意球, 间接任意球>>的状态时，所有机器人必须与对方<<禁区, 禁区>>保持至少0.2米的距离。对于已经处在<<禁区, 禁区>>内的机器人，需要在2秒内离开。

==== 干扰放球
在比赛处于<<Ball Placement, ball placement>>状态时，非放置队伍的所有机器人必须与球与放置位置之间的连线保持至少0.5米的距离（该区域形状类似于体育场），对于已经处在该区域内的机器人，需要在2秒内离开，否则记一次犯规并重新开始放球。

NOTE: 规则中没有包含所有的干扰放球的行为，所以在非放置队伍有明显的干扰放球行为时，裁判可以记该队一次犯规。

==== 碰撞
当两个不同队伍的机器人发生碰撞时，记录两个机器人速度矢量在二者连线投影上的差值，如果差值大于1.5米/秒，速度较大的机器人所在队伍记一次犯规，如果差异小于0.3米/秒，则双方各记一次犯规，但比赛不中断。

==== 推挤
当双方机器人都与球接触或者彼此接触时，机器人施力使对方机器人在自己朝向移动，这种行为被视为推挤。

NOTE: 当双方机器人都用近似的力推挤对方机器人时，双方都不犯规。

==== 控球
机器人不能将球包裹以至于对方机器人无法拿到球。

==== 翻倒或掉落零件
机器人不得翻倒，爆炸或在场地上掉落对其他机器人有潜在威胁的零件。犯规机器人必须被<<替补, 替换>>。

NOTE: 金属部件（例如螺钉）以及较大的部件通常构成潜在的威胁，非常小的非金属部件（例如橡胶圈）不会构成威胁。

==== 停止状态机器人速度
在停止的状态下机器人车速不能超过1.5米/秒，对于已超速的，需要在2秒内减速。同样的犯规每机器人每状态只记一次。

NOTE: 该规则不适用于<<放球, 放球>>状态。

NOTE: 由于停止命令是用于手动放球和机器人<<替补,替换>>的，限制机器人速度是为了避免机器人伤到场上人员。

==== 机器人离球过近
在对方进行<<开球, 开球>>、<<直接任意球, 直接任意球>>或<<间接任意球, 间接任意球>>时，机器人必须与球保持至少0.5米的距离。犯规后，比赛指令保持与犯规前一致。

NOTE: 在<<停止, 停止>>状态下，不会自动判定机器人与球的距离，但裁判可以对不遵守要求距离的队伍一张黄牌。详细参见<<停止, 停止状态>>。

==== 非守门员禁区触球

NOTE: <<犯规, 犯规>>内的判罚不适用于该规则。

如果非守门员机器人在部分进入己方禁区的情况下触球，比赛停止，记一张黄牌，判给对方一粒<<直接任意球, 直接任意球>>，犯规次数不增加。

如果非守门员机器人在完全进入己方禁区的情况下触球，比赛停止，判给对方一粒<<点球, 点球>>，犯规次数不增加。

=== Unsporting Behavior
Unsporting behavior can lead to <<Yellow Card, yellow cards>>, <<Red Card, red cards>>, <<Penalty Kick, penalty kicks>>, a <<Forced Forfeit, forced forfeit>> or a <<Disqualification, disqualification>>. The human <<Referee, referee>> chooses an appropriate sanction, depending on the severity of the offense.

NOTE: If the referee is not sure which sanction to choose, he may confer with members of the <<Technical Committee, technical committee>> or the <<Organizing Committee, organizing committee>>.

Some examples of unsporting behavior are listed below.

==== Damaging Other Robots
It is not allowed to damage or modify robots of other teams.

==== Damaging The Field Or The Ball
It is not allowed to damage or modify the field or the ball.

==== Showing Lack Of Respect
A team member must show appropriate respect to everyone involved in the game. Infringements of this rule include but are not limited to:

* insulting the opponent, the <<Referee, referee>> or other persons holding an <<Impartial Roles, impartial role>>
* annoying the <<Referee, referee>> or other persons holding an <<Impartial Roles, impartial role>>
* not obeying the orders of the <<Referee, referee>>

=== Simultaneous Offenses
If the game is <<Stop, stopped>> and a team is allowed to <<Resuming The Game, resume the game>>, <<Minor Offenses, minor offenses>> and <<Fouls, fouls>> of this team's opponent don't affect the method and position of the resumption of the game, except if the resulting method is a <<Penalty Kick, penalty kick>>.

If a team exploits this rule, the referee may punish this team for <<Unsporting Behavior,unsporting behavior>> by issuing a <<Yellow Card, yellow card>>.

NOTE: This rule is in place to prevent teams from purposely committing offenses in order to relocate the opponent <<Direct Free Kick, direct free kick>> or <<Indirect Free Kick, indirect free kick>> to a more favorable position.

=== Advantage Rule
In certain situations, stopping the game because of a foul may have a disadvantage to the opposing team.
As these situations are not easy to detect automatically, the opposing team is asked if it likes to continue the game.
In this case, the game is not stopped and no direct kick is awarded at any time.
The foul counter is still incremented and any resulting cards are given when the game is <<Stop,stopped>>.

.Fouls that are considered

* <<Crashing>>, if not both teams committed the foul
* <<Attacker Touches Robot In Opponent Defense Area>>

NOTE: If the team is not connected to the game controller or does not reply within 0.2 seconds, the decision of the team defaults to stopping the game.
