== Offensese
== 犯规
Offenses are divided into multiple categories according to the seriousness of the offense: <<Minor Offenses, minor offenses>>, <<Fouls, fouls>> and <<Unsporting Behavior, unsporting behavior>>.

NOTE: Rule of thumb: Minor offenses are infringements of the rules committed by an attacking robot while the ball is <<Ball In And Out Of Play, in play>>. Fouls are infringements of the rules committed by a defender or while the ball is <<Ball In And Out Of Play, out of play>> or infringements that may harm the humans, the robots or the field.

=== Minor Offenses
Minor offenses are violations of the rules that result in a stoppage and a subsequent <<Indirect Free Kick, indirect free kick>> for the opposing team. The free kick will be shot from the position where the offense began happening (see <<Direct Free Kick, the direct free kick rules>> for the exact ball position rules).

All minor offenses are listed below.

==== Aimless Kick [small]#(_division B only_)#
A kick is aimless when after the ball touched a robot, it subsequently crossed the midline and then its opponent's goal line outside the goal without touching another robot. A kick-off kick cannot be aimless, as the ball is located at the midline and does therefore not cross it.

==== Lack Of Progress
There is a lack of progress if only one team is allowed to <<Ball Manipulation, manipulate the ball>> (<<Kick-Off, kick-off>>, <<Direct Free Kick, direct free kick>>, <<Indirect Free Kick, indirect free kick>>, <<Penalty Kick, penalty kick>>) and does not bring the ball <<Ball In And Out Of Play, into play>> in time. The time limit is 5 seconds for <<Indirect Free Kick, indirect free kicks>> and <<Direct Free Kick, direct free kicks>> in division A and 10 seconds in all other cases.

There is also a lack of progress if the ball is inside a team's <<Defense Area, defense area>> for 10 seconds, since the keeper is the only robot that is allowed to <<Ball Manipulation, manipulate the ball>>.

NOTE: If both teams are allowed to manipulate the ball, and thus no team is at fault, the referee may stop the game and issue a <<Force Start, force start>> command.

NOTE: If both teams are clearly unable to bring the ball <<Ball In And Out Of Play, into play>> without violating the rules, the referee may issue a <<Force Start, force start>> command instead of an <<Indirect Free Kick, indirect free kick>> for the other team.

==== Double Touch
When the ball is brought <<Ball In And Out Of Play, into play>> following a <<Kick-Off, kick-off>>, <<Direct Free Kick, direct free kick>>, <<Indirect Free Kick, indirect free kick>> or <<Penalty Kick, penalty kick>>, the kicker is not allowed to touch the ball until it has been touched by another robot or the game has been stopped.

The ball must have moved at least 0.05 meters to be considered as <<Ball In And Out Of Play, in play>>.

NOTE: It is understood that the ball may be bumped by the robot multiple times over a short distance while the kick is being taken. This is why a distance of 0.05 meters is used to decide whether a robot violates this rule or not. Remaining in contact with the ball for more than 0.05 meters also counts as double touch, even though technically the robot only touched the ball once.

==== Attacker In Defense Area
A robot must not touch the ball while being partially or fully inside the opponent <<Defense Area, defense area>>.

NOTE: When the ball is <<Ball In And Out Of Play, out of play>>, the more strict rule <<Robot Too Close To Opponent Defense Area>> applies instead.

==== Excessive Dribbling
A robot must not <<Dribbling Device, dribble>> the ball further than 1 meter, measured linearly from the ball location where the dribbling started. A robot begins dribbling when it makes contact with the ball and stops dribbling when there is an observable separation between the ball and the robot.

NOTE: Dribblers can still be used to dribble large distances with the ball as long as the robot periodically loses possession, such as kicking the ball ahead of it as human soccer players often do.

==== Ball Speed
A robot must not accelerate the ball faster than 6.5 meters per second in 3D space.

=== Fouls
Fouls are violations of the rules that result in a <<Direct Free Kick, direct free kick>> for the opposing team. The free kick will be shot from the position where the offense began happening (see <<Direct Free Kick, the direct free kick rules>> for the exact ball position rules). If the foul happened while the ball is <<Ball In And Out Of Play, out of play>>, no free kick is given.

Every third foul of the same team results in a <<Yellow Card, yellow card>>.

In case of severe fouls, the referee can also issue a <<Yellow Card, yellow card>> or a <<Red Card, red card>>.

All fouls are listed below.

==== Attacker Touches Robot In Opponent Defense Area
When the ball <<Ball In And Out Of Play, in play>>, a robot must not touch any opponent robot inside the opponent <<Defense Area, defense area>>.

NOTE: When the ball is <<Ball In And Out Of Play, out of play>>, the rule <<Robot Too Close To Opponent Defense Area>> applies instead.

==== Robot Too Close To Opponent Defense Area
During <<Stop, stop>>, <<Direct Free Kick, direct free kicks>> and <<Indirect Free Kick, indirect free kicks>>, before the ball <<Resuming The Game, has entered play>>, all robots have to keep at least 0.2 meters distance to the opponent <<Defense Area, defense area>>.

There is a grace period of 2 seconds for the robots to move away from the opponent defense area.

==== Ball Placement Interference
During <<Ball Placement, ball placement>>, all robots of the non-placing team have to keep at least 0.5 meters distance to the line between the ball and the placement position (the forbidden area forms a stadium shape).

If a robot of the non-placing team is too close to the line between the ball and the placement position for more than 2 seconds, it commits a foul.
In this case, the placement procedure is restarted.

NOTE: This rule does not cover all cases of ball placement interference. The <<Referee, referee>> is encouraged to call fouls if the non-placing team is obviously interfering with the ball placement.

==== Crashing
At the moment of collision of two robots of different teams, the difference of the speed vectors of both robots is taken and projected onto the line that is defined by the position of both robots. If the length of this projection is greater than 1.5 meters per second, the faster robot committed a foul. If the absolute robot speed difference is less than 0.3 meters per second, both conduct a foul but the game will not be stopped.

==== Pushing
A robot pushes an opponent robot if both robots keep contact to the ball or to each other while the robot exerts force onto the opponent robot, such that both robots travel towards the opponent robot.

NOTE: If both robots are pushing each other with similar force, no team is at fault.

==== Ball Holding
Robots must not surround the ball to prevent access by others.

==== Tipping Over Or Dropping Parts
A robot must not tip over, break or drop parts on the field that pose a potential threat to other robots.

A robot violating this rule has to be <<Robot Substitution, substituted>>.

NOTE: Metal parts (screws for example) as well as larger parts generally pose a potential threat, very small non-metal parts (for example rubber subwheel rings) don't.

==== Robot Stop Speed
A robot must not move faster than 1.5 meters per second during <<Stop, stop>>. A violation of this rule is only counted once per robot and stoppage.

There is a grace period of 2 seconds for the robots to slow down.

NOTE: This rule does not apply to <<Ball Placement, ball placement>>.

NOTE: Since the stop command is used for manual ball placement and <<Robot Substitution, robot substitution>>, the intention of the robot speed limit is to avoid robots harming the people on the field.

==== Defender Too Close To Ball
A robot's distance to the ball must be at least 0.5 meters during an opponent <<Kick-Off, kick-off>>, <<Direct Free Kick, direct free kick>> or <<Indirect Free Kick, indirect free kick>>.
The game is resumed with the same command that was issued before the foul.

NOTE: During <<Stop, stop>>, there is no automatic sanction for being too close to the ball. The referee may still punish a team for <<Unsporting Behavior,unsporting behavior>> by issuing a <<Yellow Card, yellow card>> if it does not respect the required distance. See <<Stop, stop>> for further explanation.

==== Multiple Defenders
NOTE: This rule does not use the standard sanctions defined for <<Fouls, fouls>>.

If a robot other than the keeper touches the ball while being partially inside its own defense area, the game is stopped, the robot receives a <<Yellow Card, yellow card>> and the opponent team resumes the game with a <<Direct Free Kick, direct free kick>>. The foul counter is not increased.

If a robot other than the keeper touches the ball while being entirely inside its own defense area, the game is stopped and a <<Penalty Kick, penalty kick>> is awarded to the other team. The foul counter is not increased.


=== 违背体育精神的行为
违背体育精神的行为会导致 <<Yellow Card, yellow cards>>, <<Red Card, red cards>>, <<Penalty Kick, penalty kicks>>, a <<Forced Forfeit, forced forfeit>> or a <<Disqualification, disqualification>>. <<Referee, referee>> 会根据犯规的严重程度选择适当的处罚。

注意：如果裁判员不知道选择什么处罚，他可以向 <<Technical Committee, technical committee>> 或者 <<Organizing Committee, organizing committee>> 的成员咨询。

下面列出一些违背体育精神行为的示例。

==== 破坏其他机器人
不允许破坏或改装其他队伍的机器人。

==== 破坏场地或比赛用球
不允许破坏或改变场地或比赛用球

==== 缺乏尊重
团队成员必须对参与比赛的每一个人表现出适当的尊重。违反本规则的行为包括但不限于：
*侮辱对手、<Referee, referee>> 或其他担任 <<Impartial Roles, impartial role>> 的人
*激怒 <<Referee, referee>> 或其他担任 <<Impartial Roles, impartial role>> 的人
*不遵守 <<Referee, referee>> 的指令

=== 同时犯规
如果游戏 <<Stop, stopped>> 并且一个队伍被允许 <<Resuming The Game, resume the game>> ，该队伍对手的 <<Minor Offenses, minor offenses>> 和 <<Fouls, fouls>>不会影响恢复游戏的方法与位置， 除非结果方法是
<<Penalty Kick, penalty kick>>。

如果一个队伍利用了这个规则，裁判员可以签发一张 <<Yellow Card, yellow card>> 来惩罚该队伍的 <<Unsporting Behavior,unsporting behavior>>。

注意：该规则旨在防止队伍故意犯规，以便将对手的 <<Direct Free Kick, direct free kick>> 或 <<Indirect Free Kick, indirect free kick>> 重新定位到更有利的位置。

=== Advantage Rule
在某些情况下，由于犯规而停止比赛可能对对方不利。
由于这些情况不容易自动检测到，因此会询问对方是否选择继续比赛。
在这种情况下，游戏不会停止，也不会授予任意球。
当游戏 <<stop，stopped>> 时，犯规计数器仍然递增，并仍会给出红黄牌。

犯规会被认为是：

* <<Crashing>> 如果不是两个队都犯规的话
* <<Attacker Touches Robot In Opponent Defense Area>>

注意：如果团队没有连接到游戏控制器或在0.2秒内没有回复，则团队的决定默认为停止游戏。
