== 裁判指令

=== 停止比赛
==== 停止
.定义
当发出停止指令时，所有的机器人必须减速到低于1.5m/s。此外，所有的机器人必须跟球保持至少0.5米的距离，并且不允许<<Ball Manipulation, 操纵球>>。

NOTE: 如果球运动得很快，一直跟球保持要求的距离是困难的，尤其是在停止时机器人的速度被限制的情况下。因此，如果裁判认为机器人在尽其所能地遵守这条距离规则就足够了。

.使用
停止指令在球越过<<Field Lines, 边线>>（包括球门）、发生犯规、准备开始比赛、终止比赛后恢复比赛、技术暂停和自动放球的情况下，用于暂停比赛。机器人的速度限制和跟球保持的最小距离允许裁判或者助理裁判没有干扰地安全地放球。

==== 终止
.定义
当发出终止指令时，所有机器人都不允许移动或者<<Ball Manipulation, 操纵球>>。

这里留有2秒的宽限期给机器人刹车。

.使用
终止指令允许裁判在任何突发事件发生时（例如一个机器人失去控制），立即中断比赛。它也用于在比赛中当图像专家认为有必要和裁判同意时重新校准图像，以及<<Robot Substitution, 替换机器人>>。此外，裁判可以按意愿自由地发出终止指令。

终止指令经常伴随着停止指令。


=== 放球
.定义
在比赛停止后，依据发生的事件，球必须被放置在合适的位置。由队伍的机器人完成的没有人工干预的自动放球是把球放在场上指定位置的优先方式。
如果这没能完成，<<Referee, 裁判>>将人工放球。

球会被认为由机器人成功放置，如果

* 放球指令发出后没有超过30秒
* 如果下一个指令是放球队伍的<<Indirect Free Kick, 间接任意球>>或者<<Direct Free Kick, 直接任意球>>，没有机器人在距离球的0.05米范围内
* 如果下一个指令是<<Force Start, 强制开始>>，没有机器人在距离球的0.5米范围内
* 球是静止的
* 球在距离要求位置的0.15米范围内

<<Game Controller, 比赛控制器>>不会发出更多的指令，直到自动放球完成。
一旦球被成功放置，且在放球指令发出后不早于2秒，<<Game Controller, 比赛控制器>>会让比赛继续。
失败的放球会导致对手的一次间接任意球。
如果对手也放球失败，球会被<<Referee, 裁判>>放置，且比赛继续之前的指令。

非放球的队伍不可以<<Ball Placement Interference, 干扰放球>>。

.使用
当出现<<Ball In And Out Of Play, 死球>>时，下列规则决定是否要进行自动放球:

. 开球和点球时，<<Referee, 裁判>>必须放球
. 对于<<Indirect Free Kick, 间接任意球>>或者<<Direct Free Kick, 直接任意球>>，<<Ball In And Out Of Play, 开球>>的队伍必须放球
. 对于<<Force Start, 强制开始>>，随机决定放球的队伍
. 在放球开始前，球必须可见和不在场地角落、球门角落或者球门后面
. <<Referee, 裁判>>可以在任何时候决定手动放球
. <<Referee, 裁判>>可以决定在比赛的剩余时间禁用自动放球。TC/OC必须同意这个决定
. 当一个队伍连续五次放球失败，它将不被允许在比赛半场的剩余时间放球。当球出边线时对手将获得任意球。对于其他违反规则的行为或者当双方队伍都放球失败时，球会被<<Referee, 裁判>>放置
. 如果没有队伍能够放球，球会被<<Referee, 裁判>>或者<<Assistant Referee, 助理裁判>>放置。建议裁判和助理裁判使用放球工具（一个黑色长杆的装置）来放球。

NOTE: 如果球已经在应该放置的位置（例如在另一支队伍失败的任意球后），放球会在没有机器人操纵球的情况下被认为是成功的。这可能会导致在放球队伍没有真正完成一次放球的情况下，放球失败的计数被重置。

NOTE: 当放球指令发出时，球可能仍在运动。

放球对于A组的所有队伍是强制的。
B组的队伍可以在比赛前或者比赛中的任何时间，通过跟<<Referee, 裁判>>沟通，决定在比赛的剩余时间不要放球，随后裁判会告诉<<Game Controller Operator, 比赛控制器的操作者>>禁用该队伍的放球。
这种情况下，该队伍允许在对手放球后开球。
如果对手放球失败或者没有队伍能够放球，<<Referee, 裁判>>或者<<Assistant Referee, 助理裁判>>将放球。


=== 恢复比赛
在放球后，比赛将通过以下指令恢复。

// In division A, the ball will be placed automatically by the robots if the following command is a free kick or force start (see <<Ball Placement>>).

==== 标准开始
.定义
这是一个两阶段的裁判指令，当标准开始指令发出时，进攻车可以<<Ball Manipulation, 操纵球>>。比赛不能通过标准开始指令直接恢复。

.使用
标准开始指令用于<<Kick-Off, 开球>>、<<Penalty Kick, 点球>>和<<Shoot-Out, 一对一>>.

==== 开球
.定义
球必须被人类裁判放在场地中心。

当发出开球指令时，所有的机器人必须移动到自己的半场，且不在<<Center Circle, 中场圆圈>>内。然而，进攻方的一个机器人会被允许进入整个中场圆圈。这个机器人会被认为是开球车。其他机器人不允许碰球。

当<<Normal Start, 标准开球>>指令发出时，开球车被允许踢球。可以直接通过开球进球。

当球处于<<Ball In And Out Of Play, 活球>>状态时，开球车不能碰球直到它被别的机器人碰到或者比赛被停止（参见<<二次触球, 二次触球>>)。同时，机器人位置的限制被解除。

.使用
半场和加时赛（若有）通过开球开始。<<比赛准备, 比赛准备>>这一章描述了如何确定进攻方。

另外，在一方进球后，另一方通过开球重新开始比赛。

==== 直接任意球
.定义
任意球放置的位置取决于导致任意球的事件。如果距离所有<<Field Lines, 边线>>至少0.2米和距离对方<<Defense Area, 防守区域>>至少1米，则此位置有效。如果一次事件要求将球放置在违反此规则的位置，则必须将其放置在最接近的有效位置。

当发出直接任意球命令时，允许攻击方的机器人接近球，而防守方的机器人仍然必须与球保持至少0.5米的距离（与停止指令相同的距离）。攻击队的一个机器人被允许踢球，这个机器人将被认为是开球车。直接任意球可以直接进球得分。

当球处于<<Ball In And Out Of Play, 活球>>状态时，开球车不得触球，直到球被其他机器人触碰或者比赛已经停止（见<<Double Touch, 二次触球>>）。此外，对于机器人位置的限制将被解除。

.使用
在<<Fouls, 犯规>>发生后，直接任意球被用来重新开始比赛。此外，<<Goal Kick, 球门球>>和<<Corner Kick, 角球>>被认为是直接任意球。

==== 间接任意球
.定义
间接任意球的行为类似于<<Direct Free Kick, 直接任意球>>，除了：在间接任意球之后，只有在球处于<<Resuming The Game, 活球>>状态后，并且在进入防守球队的球门之前球触及进攻球队的机器人时才算进球。如果球进入防守队伍的球门而没有接触攻击机器人，则会被视为越过球门外的球门线。

如果球进入攻击方的球门（一个乌龙球），将记为防守球队进球得分。

NOTE: 通过间接任意球得分进球不需要多个攻击机器人。如果防守方的机器人在攻击方开任意球的机器人进球前触球，同样也算进球。

NOTE: 在英式足球中，如果任何球员（包括守门员）在进球前接触球就足够了。为了避免球队直接射门并希望守门员能接触到球，小型组的规则需要攻击方机器人二次接触球。

.使用
在发生<<Minor Offenses, 轻微犯规>>后，间接任意球用于重新开始比赛。此外，<<Throw-In, 边线球>>被认为是间接任意球。

==== 强制开始
.定义
当发出强制开始指令时，游戏立即恢复，并且允许两个队伍再次接近并<<Ball Manipulation, 操纵球>>。

.使用
如果在两队都被允许接近并<<Ball Manipulation, 操纵球>>的情况下至少10秒没有明显的进展，裁判可以发出一个停止命令，然后强制开始。

当比赛必须停止并且没有队伍或两个队伍都有过错时，它也可用于恢复游戏。

==== 点球
.定义
要发起罚球，必须发出停止指令并且必须由人类<<Referee, 裁判>>将球放在<<Penalty Mark, 点球点>>上。

当发出点球指令时，允许一个攻击机器人接近但不能触球。这个机器人将被称为点球手。防守守门员必须触及球门线。所有其他机器人必须在点球点往后0.4米与球门线平行的线后移动。当满足这些条件时，裁判可以发出<<Normal Start, 标准开始>>命令。

当发出<<Normal Start, 标准开始>>指令时，允许点球手踢球。点球可以直接射门得分，

当球处于<<Ball In And Out Of Play, 活球>>的状态时，踢球者不得触球，直到被其他机器人触碰或者比赛已经停止（见<<Double Touch, 二次触球>>）。此外，对于机器人位置的限制将会解除。

在每个半场结束时或加时赛结束时，允许额外的时间进行点球。

如果进攻球队违反规则并且球进入球门或者防守球队违反规则并且球没有进入球门，将重新进行点球。

.使用
罚球被用来惩罚那些收到多张<<Yellow Card, 黄牌>>的球队，以及惩罚<<Unsporting Behavior, 违反体育道德的行为>>和<<Multiple Defenders, 多个防守者>>。


=== 制裁

==== 黄牌
.定义
黄牌只能在<<Halt, 终止>>期间给出。

如果黄牌是<<Unsporting Behavior, u违反体育道德的行为>>的结果，则裁判可以决定立即<<Halt, 终止>>比赛。在这种情况下，另一支球队将获得直接任意球。

收到黄牌后，受罚球队场上允许的机器人数量减少一个。如果在减少之后，团队拥有的机器人数量超过现场允许的数量，则必须在<<Resuming The Game, 恢复比赛>>前<<Robot Substitution, 拿走>>机器人。受惩罚的团队可以选择要移除的机器人。

在120秒的比赛时间（由比赛控制器测量）后，黄牌到期并且允许的机器人的数量将增加1。团队可以在下一次机会中<<Robot Substitution, 放入机器人>>。

一支球队的每获得第三张牌（无论其颜色如何），对手球队都会获得<<Penalty Kick, 点球>>。

.使用
黄牌被用于惩罚多次<<Fouls, 犯规>>的球队。

裁判员也可以给出黄牌以惩罚<<Fouls, 犯规>> 或<<Unsporting Behavior, 违反体育道德的行为>>。

==== 红牌
.定义
红牌与<<Yellow Card, 黄牌>>相似，不同之处在于它直到比赛结束才到期。

.使用
裁判员会给出红牌，以惩罚严重的<<Fouls, 犯规>>或<<Unsporting Behavior, 违反体育道德的行为>>。

NOTE: 例如，机器人的严重暴力接触或对裁判的不尊重行为可能导致红牌。


==== 强制弃赛
.定义
强制弃赛意味着一支球队立即以0比10的分数输掉当前比赛。

.使用
如果团队无法提供至少一个满足规则的机器人进行比赛，则可能被强制弃赛。

只有在与<<Technical Committee, 技术委员会>>和<<Organizing Committee, 组织委员会>>成员达成协议的情况下，队伍才能被强制弃赛。

==== 取消比赛资格
.定义
取消资格意味着一支球队立即退出锦标赛并排在最后。它没有资格获得任何奖杯。

.使用
如果该团队的成员不遵守安全准则，场地规则或几次犯相似的严重违规行为，则队伍可能被取消资格。

只有在与<<Technical Committee, 技术委员会>>和<<Organizing Committee, 组织委员会>>成员达成协议的情况下，队伍才能被取消资格。
