== 裁判指令

=== 停止比赛
==== 停止
.定义
当发出停止指令时，所有的机器人必须减速到低于1.5m/s。此外，所有的机器人必须跟球保持至少0.5米的距离，并且不允许<<Ball Manipulation, 操纵球>>。

NOTE: 如果球运动得很快，一直跟球保持要求的距离是困难的，尤其是在停止时机器人的速度被限制的情况下。因此，如果裁判认为机器人在尽其所能地遵守这条距离规则就足够了。

.使用
停止指令在球越过<<Field Lines, 边线>>（包括球门）、发生犯规、准备开始比赛、终止比赛后恢复比赛、技术暂停和自动放球的情况下，用于暂停比赛。机器人的速度限制和跟球保持的最小距离允许裁判或者助理裁判没有干扰地安全地放球。

==== 终止
.定义
当发出终止指令时，所有机器人都不允许移动或者<<Ball Manipulation, 操纵球>>。

这里留有2秒的宽限期给机器人刹车。

.使用
终止指令允许裁判在任何突发事件发生时（例如一个机器人失去控制），立即中断比赛。它也用于在比赛中当图像专家认为有必要和裁判同意时重新校准图像，以及<<Robot Substitution, 替换机器人>>。此外，裁判可以按意愿自由地发出终止指令。

终止指令经常伴随着停止指令。


=== 放球
.定义
在比赛停止后，依据发生的事件，球必须被放置在合适的位置。由队伍的机器人完成的没有人工干预的自动放球是把球放在场上指定位置的优先方式。
如果这没能完成，<<Referee, 裁判>>将人工放球。

球会被认为由机器人成功放置，如果

* 放球指令发出后没有超过30秒
* 如果下一个指令是放球队伍的<<Indirect Free Kick, 间接任意球>>或者<<Direct Free Kick, 直接任意球>>，没有机器人在距离球的0.05米范围内
* 如果下一个指令是<<Force Start, 强制开始>>，没有机器人在距离球的0.5米范围内
* 球是静止的
* 球在距离要求位置的0.15米范围内

<<Game Controller, 比赛控制器>>不会发出更多的指令，直到自动放球完成。
一旦球被成功放置，且在放球指令发出后不早于2秒，<<Game Controller, 比赛控制器>>会让比赛继续。
失败的放球会导致对手的一次间接任意球。
如果对手也放球失败，球会被<<Referee, 裁判>>放置，且比赛继续之前的指令。

非放球的队伍不可以<<Ball Placement Interference, 干扰放球>>。

.使用
当出现<<Ball In And Out Of Play, 死球>>时，下列规则决定是否要进行自动放球:

. 开球和点球时，<<Referee, 裁判>>必须放球
. 对于<<Indirect Free Kick, 间接任意球>>或者<<Direct Free Kick, 直接任意球>>，<<Ball In And Out Of Play, 开球>>的队伍必须放球
. 对于<<Force Start, 强制开始>>，随机决定放球的队伍
. 在放球开始前，球必须可见和不在场地角落、球门角落或者球门后面
. <<Referee, 裁判>>可以在任何时候决定手动放球
. <<Referee, 裁判>>可以决定在比赛的剩余时间禁用自动放球。TC/OC必须同意这个决定
. 当一个队伍连续五次放球失败，它将不被允许在比赛半场的剩余时间放球。当球出边线时对手将获得任意球。对于其他违反规则的行为或者当双方队伍都放球失败时，球会被<<Referee, 裁判>>放置
. 如果没有队伍能够放球，球会被<<Referee, 裁判>>或者<<Assistant Referee, 助理裁判>>放置。建议裁判和助理裁判使用放球工具（一个黑色长杆的装置）来放球。

NOTE: 如果球已经在应该放置的位置（例如在另一支队伍失败的任意球后），放球会在没有机器人操纵球的情况下被认为是成功的。这可能会导致在放球队伍没有真正完成一次放球的情况下，放球失败的计数被重置。

NOTE: 当放球指令发出时，球可能仍在运动。

放球对于A组的所有队伍是强制的。
B组的队伍可以在比赛前或者比赛中的任何时间，通过跟<<Referee, 裁判>>沟通，决定在比赛的剩余时间不要放球，随后裁判会告诉<<Game Controller Operator, 比赛控制器的操作者>>禁用该队伍的放球。
这种情况下，该队伍允许在对手放球后开球。
如果对手放球失败或者没有队伍能够放球，<<Referee, 裁判>>或者<<Assistant Referee, 助理裁判>>将放球。


=== 恢复比赛
在放球后，比赛将通过以下指令恢复。

// In division A, the ball will be placed automatically by the robots if the following command is a free kick or force start (see <<Ball Placement>>).

==== 标准开始
.定义
这是一个两阶段的裁判指令，当标准开始指令发出时，进攻车可以<<Ball Manipulation, 操纵球>>。比赛不能通过标准开始指令直接恢复。

.使用
标准开始指令用于<<Kick-Off, 开球>>、<<Penalty Kick, 点球>>和<<Shoot-Out, 一对一>>.

==== 开球
.定义
球必须被人类裁判放在场地中心。

当发出开球指令时，所有的机器人必须移动到自己的半场，且不在<<Center Circle, 中场圆圈>>内。然而，进攻方的一个机器人会被允许进入整个中场圆圈。这个机器人会被认为是开球车。其他机器人不允许碰球。

当<<Normal Start, 标准开球>>指令发出时，开球车被允许踢球。可以直接通过开球进球。

当球处于<<Ball In And Out Of Play, 活球>>状态时，开球车不能碰球直到它被别的机器人碰到或者比赛被停止（参见<<二次触球, 二次触球>>)。同时，机器人位置的限制被解除。

.使用
半场和加时赛（若有）通过开球开始。<<比赛准备, 比赛准备>>这一章描述了如何确定进攻方。

另外，在一方进球后，另一方通过开球重新开始比赛。

==== Direct Free Kick
.Definition
The ball placement position for a free kick depends on the event that led to the free kick. This position is valid if there is at least 0.2 meters distance to all <<Field Lines, field lines>> and 1 meter distance to either <<Defense Area, defense area>>. If an event requires the ball to be placed at a position that contravenes this rule, it has to be placed at the closest valid position instead.

When the direct free kick command is issued, robots of the attacking team are allowed to approach the ball while robots of the defending team still have to stay at least 0.5 meters distance away from the ball (the same distance as in stop). One robot of the attacking team is allowed to shoot the ball. This robot will be referred to as the kicker. A goal may be scored directly from the direct free kick.

When the ball is <<Ball In And Out Of Play, in play>>, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

.Usage
Direct free kicks are used to restart the game after a <<Fouls, foul>> has occured. Additionally, <<Goal Kick, goal kicks>> and <<Corner Kick, corner kicks>> are mapped to direct free kicks.

==== Indirect Free Kick
.Definition
An indirect free kick behaves like a <<Direct Free Kick,direct free kick>>, except: After an indirect free kick, a goal can only be scored if the ball touches a robot of the attacking team after the ball <<Resuming The Game, entered play>> and before it entering the goal of the defending team. If the ball enters the goal of the defending team without touching an attacking robot, it will be treated like it crossed the goal line outside the goal.

If the ball enters the goal of the attacking team (an own goal), a goal will be awarded to the defending team.

NOTE: Scoring a goal from an indirect free kick does not require more than one attacking robot. The goal can also be shot by the same robot that kicked the free kick if a robot of the defending team touches the ball before the attacker shoots the goal.

NOTE: In association football, it is sufficient if any player (including the keeper) touches the ball before it enters the goal. To discourage the teams to shoot directly at the goal and hope that the keeper touches it, the rules of the Small Size League require a second touch of an attacking robot.

.Usage
Indirect free kicks are used to restart the game after a <<Minor Offenses, minor offense>> has occured. Additionally, <<Throw-In, throw-ins>> are mapped to indirect free kicks.

==== Force Start
.Definition
When the force start command is issued, the game is immediately resumed and both teams are allowed to approach and <<Ball Manipulation, manipulate the ball>> again.

.Usage
The referee can issue a stop command followed by force start if there is a clear lack of progress for at least 10 seconds while both teams are allowed to approach and <<Ball Manipulation, manipulate the ball>>.

It can also be used to resume the game when the game had to be stopped and no team or both teams are at fault.

==== Penalty Kick
.Definition
To initiate a penalty kick, the stop command has to be sent and the ball has to be placed on the <<Penalty Mark, penalty mark>> by the human <<Referee, referee>>.

When the penalty command is issued, one attacking robot is allowed to approach but not touch the ball. This robot will be referred to as the kicker. The defending keeper has to touch the goal line. All other robots have to move behind a line parallel to the goal line and 0.4 meters behind the penalty mark. When these constraints are met, the referee may continue with a <<Normal Start, normal start>> command.

When the <<Normal Start, normal start>> command is issued, the kicker is allowed to shoot the ball. A goal may be scored directly from the penalty kick.

When the ball is <<Ball In And Out Of Play, in play>>, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

Additional time is allowed for a penalty kick to be taken at the end of each half or at the end of periods of overtime.

The penalty kick is retaken if the attacking team infringes the rules and the ball enters the goal or the defending team infringes the rules and the ball does not enter the goal.

.Usage
Penalty Kicks are used to punish teams that received multiple <<Yellow Card, yellow cards>>, as well as to punish <<Unsporting Behavior, unsporting behavior>> and <<Multiple Defenders, multiple defenders>>.


=== Sanctions

==== Yellow Card
.Definition
A yellow card can only be given during <<Halt, halt>>.

If the yellow card is shown as a result of <<Unsporting Behavior, unsporting behavior>>, the referee may decide to immediately <<Halt, halt>> the match. In this case, the match continues with a direct free kick for the other team.

Upon receipt of a yellow card, the number of robots allowed on the field for the penalized team decreases by one. If, after this decrease, the team has more robots than permitted on the field, a robot must be <<Robot Substitution, taken out>> before <<Resuming The Game, play resumes>>. The penalized team can choose the robot to remove.

After 120 seconds of playing time (measured by the game controller), the yellow card expires and the number of allowed robots is increased by one. The team may <<Robot Substitution, put a robot back in>> during the next opportunity.

For every third card (regardless of its color) for one team, a <<Penalty Kick, penalty kick>> is awarded to the opponent team.

.Usage
Yellow cards are used to punish teams that committed multiple <<Fouls, fouls>>.

Yellow cards can also be given by the referee to punish <<Fouls, fouls>> or <<Unsporting Behavior,unsporting behavior>>.

==== Red Card
.Definition
A red card behaves like a <<Yellow Card, yellow card>>, exept: It does not expire until the end of the game.

.Usage
Red cards are given by the referee to punish severe <<Fouls, fouls>> or <<Unsporting Behavior,unsporting behavior>>.

NOTE: For example, serious violent contact by the robots or disrespectful behavior towards the referees can result in a red card.


==== Forced Forfeit
.Definition
A Forced forfeit means that a team instantly loses the current game with a score of 0 to 10.

.Usage
A team can be forced to forfeit if it is unable to play with at least one robot that satisfies the rules.

A team can only be forced to forfeit in agreement with members of the <<Technical Committee, technical committee>> and the <<Organizing Committee, organizing committee>>.

==== Disqualification
.Definition
A Disqualification means that a team immediately drops out of the tournament and places last. It will not be eligible to receive any trophies.

.Usage
A team can be disqualified if members of this team don't follow safety guidelines, rules of the venue or commit similarly severe offenses.

A team can only be disqualified in agreement with members of the <<Technical Committee, technical committee>> and the <<Organizing Committee, organizing committee>>.
